# -*- coding: utf-8 -*-
"""Image Registration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qnui02UfbkXQPYEL0Q28J1U89W3aO1wC
"""

import cv2
from matplotlib import pyplot as plt

def split_collage(image):
    height, width = image.shape[:2]
    mid_width = width // 2
    img1 = image[:, :mid_width]
    img2 = image[:, mid_width:]
    return img1, img2

collage = cv2.imread('/content/The-same-face-under-two-different-lighting-conditions.png', cv2.IMREAD_COLOR)

image1, image2 = split_collage(collage)

image1 = cv2.cvtColor(image1, cv2.COLOR_BGR2RGB)
image2 = cv2.cvtColor(image2, cv2.COLOR_BGR2RGB)

orb = cv2.ORB_create()

kp1, des1 = orb.detectAndCompute(image1, None)
kp2, des2 = orb.detectAndCompute(image2, None)

bf = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=True)
matches = bf.match(des1, des2)

matches = sorted(matches, key=lambda x: x.distance)

line_thickness = 0.0001

image3 = cv2.drawMatches(
    image1, kp1, image2, kp2, matches[:10], None,
    flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS,
)

plt.figure(figsize=(10, 5))
plt.imshow(image3)
plt.axis('off')
plt.show()